# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webm_app', '0002_payanddisplaymachine_payanddisplayoutlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='clearway',
            field=models.TextField(null=True, verbose_name='Machine is in a clearway zone'),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='furtherinfo',
            field=models.TextField(null=True, verbose_name='Further information'),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='furtherloc',
            field=models.TextField(null=True, verbose_name='Further description of location'),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='hours',
            field=models.TextField(null=True, verbose_name='The hours of operation'),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='location',
            field=models.TextField(null=True, verbose_name='Text location'),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Longitude co-ordinate'),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='nospaces',
            field=models.TextField(null=True, verbose_name='Number of total parking spaces in street/area'),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='tariff',
            field=models.FloatField(null=True, verbose_name='Price per hour'),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='zone',
            field=models.TextField(null=True, verbose_name='What zone the P&D machine is in'),
        ),
    ]
