# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webm_app', '0003_auto_20170421_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payanddisplayoutlet',
            name='address1',
            field=models.TextField(null=True, verbose_name='First address field'),
        ),
        migrations.AlterField(
            model_name='payanddisplayoutlet',
            name='address2',
            field=models.TextField(null=True, verbose_name='Second address field'),
        ),
        migrations.AlterField(
            model_name='payanddisplayoutlet',
            name='county',
            field=models.TextField(null=True, verbose_name='County or Dublin area code'),
        ),
        migrations.AlterField(
            model_name='payanddisplayoutlet',
            name='name',
            field=models.TextField(null=True, verbose_name='Name of outlet'),
        ),
    ]
