# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webm_app', '0004_auto_20170421_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Longitude co-ordinate'),
            preserve_default=False,
        ),
    ]
