# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webm_app', '0005_auto_20170421_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='clearway',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='furtherinfo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='furtherloc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='hours',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='nospaces',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='tariff',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payanddisplaymachine',
            name='zone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payanddisplayoutlet',
            name='address1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payanddisplayoutlet',
            name='address2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payanddisplayoutlet',
            name='county',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payanddisplayoutlet',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payanddisplayoutlet',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payanddisplayoutlet',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
