# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 20:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webm_app', '0006_auto_20170421_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='payanddisplaymachine',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='payanddisplayoutlet',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
